import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Header from "./components/Header";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} min-h-screen `}
      >
        <Header /> 
        <main className="container max-w-[1240px] flex justify-center items-center m-auto ">
          {children}
        </main>
        <ToastContainer position="top-center"/>
      </body>
    </html>
  );
}
